# Generated by Django 6.0.5 on 2026-05-21 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi', '0005_rename_created_at_message_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='multi.room'),
            preserve_default=False,
        ),
    ]
